### ISSUE TITLE
cjpeg error？

### ISSUE THREAD

**Issue by jhsy0330** [chenzhutian/hexo-all-minifier#104]
FATAL {
  err: Error: spawn /home/jhsy/hexo/node_modules/mozjpeg/vendor/cjpeg ENOENT
      at Process.ChildProcess._handle.onexit (internal/child_process.js:268:19)
      at onErrorNT (internal/child_process.js:464:16)
      at processTicksAndRejections (internal/process/task_queues.js:80:21) {
    errno: -2,
    code: 'ENOENT',
    syscall: 'spawn /home/jhsy/hexo/node_modules/mozjpeg/vendor/cjpeg',
    path: '/home/jhsy/hexo/node_modules/mozjpeg/vendor/cjpeg',
    spawnargs: [ '-baseline' ],
    stdout: <Buffer >,
    stderr: <Buffer >,
    failed: true,
    signal: null,
    cmd: '/home/jhsy/hexo/node_modules/mozjpeg/vendor/cjpeg -baseline',
    timedOut: false,
    killed: false
  }
}

**Comment by kusime** [comment]
me too

**Comment by yfengn** [comment]
Hello, is there a solution？

**Comment by clarence-glx** [comment]
any body??

**Comment by leiqichn** [comment]
any body?
