### ISSUE TITLE
Unexpected token: operator (>) 

### ISSUE THREAD

**Issue by wafer-li** [chenzhutian/hexo-all-minifier#24]
It seems that the js-minifier cannot recognize the lambda operator (`=>`)

Full stack trace：

```
ERROR Asset render failed: lib/canvas-ribbon/canvas-ribbon.js
SyntaxError: Unexpected token: operator (>)
    at JS_Parse_Error.get (eval at <anonymous> (/Users/wafer/Documents/wafer-li.github.io/node_modules/hexo-all-minifier/node_modules/uglify-js/tools/node.js:1:1), <anonymous>:86:23)
    at getFullErrorStack (/Users/wafer/Documents/wafer-li.github.io/node_modules/bunyan/lib/bunyan.js:1129:17)
    at Object.Logger.stdSerializers.err (/Users/wafer/Documents/wafer-li.github.io/node_modules/bunyan/lib/bunyan.js:1147:16)
    at /Users/wafer/Documents/wafer-li.github.io/node_modules/bunyan/lib/bunyan.js:873:50
    at Array.forEach (native)
    at Logger._applySerializers (/Users/wafer/Documents/wafer-li.github.io/node_modules/bunyan/lib/bunyan.js:865:35)
    at mkRecord (/Users/wafer/Documents/wafer-li.github.io/node_modules/bunyan/lib/bunyan.js:978:17)
    at Logger.<anonymous> (/Users/wafer/Documents/wafer-li.github.io/node_modules/bunyan/lib/bunyan.js:1044:19)
    at /Users/wafer/Documents/wafer-li.github.io/node_modules/hexo/lib/plugins/generator/asset.js:36:22
    at tryCatcher (/Users/wafer/Documents/wafer-li.github.io/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/wafer/Documents/wafer-li.github.io/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/wafer/Documents/wafer-li.github.io/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/wafer/Documents/wafer-li.github.io/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/wafer/Documents/wafer-li.github.io/node_modules/bluebird/js/release/promise.js:689:18)
    at Async._drainQueue (/Users/wafer/Documents/wafer-li.github.io/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/Users/wafer/Documents/wafer-li.github.io/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/Users/wafer/Documents/wafer-li.github.io/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
```
canvas-ribbon.js at 
https://github.com/iissnan/hexo-theme-next/blob/master/source/lib/canvas-ribbon/canvas-ribbon.js

**Comment by chenzhutian** [comment]
Please have a try the latest version v0.2.2
I have upgraded the uglify-js to uglify-es
@wafer-li

**Comment by chenzhutian** [comment]
close by inactive
