### ISSUE TITLE
js_concator 有这个问题

### ISSUE THREAD

**Issue by andot** [chenzhutian/hexo-all-minifier#52]
js_concator 开启时会有这个问题，看上去像是script里面有undefined的值，不知道为什么。

```js
TypeError: Cannot read property 'on' of undefined
    at Promise (/mnt/d/Git/CoolCode/node_modules/hexo-all-minifier/lib/concatJS.js:117:18)
    at Promise._execute (/mnt/d/Git/CoolCode/node_modules/bluebird/js/release/debuggability.js:303:9)
    at Promise._resolveFromExecutor (/mnt/d/Git/CoolCode/node_modules/bluebird/js/release/promise.js:483:18)
    at new Promise (/mnt/d/Git/CoolCode/node_modules/bluebird/js/release/promise.js:79:10)
    at Promise.all.scripts.map.path (/mnt/d/Git/CoolCode/node_modules/hexo-all-minifier/lib/concatJS.js:114:16)
    at Array.map (<anonymous>)
    at Promise.all.then.then (/mnt/d/Git/CoolCode/node_modules/hexo-all-minifier/lib/concatJS.js:113:34)
    at tryCatcher (/mnt/d/Git/CoolCode/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/mnt/d/Git/CoolCode/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/mnt/d/Git/CoolCode/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/mnt/d/Git/CoolCode/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/mnt/d/Git/CoolCode/node_modules/bluebird/js/release/promise.js:693:18)
    at Promise._fulfill (/mnt/d/Git/CoolCode/node_modules/bluebird/js/release/promise.js:638:18)
    at Promise._resolveCallback (/mnt/d/Git/CoolCode/node_modules/bluebird/js/release/promise.js:432:57)
    at Promise._settlePromiseFromHandler (/mnt/d/Git/CoolCode/node_modules/bluebird/js/release/promise.js:524:17)
    at Promise._settlePromise (/mnt/d/Git/CoolCode/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/mnt/d/Git/CoolCode/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/mnt/d/Git/CoolCode/node_modules/bluebird/js/release/promise.js:693:18)
    at Promise._fulfill (/mnt/d/Git/CoolCode/node_modules/bluebird/js/release/promise.js:638:18)
    at PromiseArray._resolve (/mnt/d/Git/CoolCode/node_modules/bluebird/js/release/promise_array.js:126:19)
    at PromiseArray._promiseFulfilled (/mnt/d/Git/CoolCode/node_modules/bluebird/js/release/promise_array.js:144:14)
    at Promise._settlePromise (/mnt/d/Git/CoolCode/node_modules/bluebird/js/release/promise.js:574:26)
```

**Comment by harlley** [comment]
Same error here ;(

**Comment by 467815891a** [comment]
Same error here，too

**Comment by KumaNNN** [comment]
> Cannot read property 'on' of undefined
不能读取未定义的属性`on`

即，这个属性在配置文件中缺少，通常为注释掉了。
