### ISSUE TITLE
Error: write EOF

### ISSUE THREAD

**Issue by HarborZeng** [chenzhutian/hexo-all-minifier#73]
After run `hexo s`, some `INFO update Optimize IMG......`showed, and then 
```shell
FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html
Error: write EOF
    at _errnoException (util.js:992:11)
    at WriteWrap.afterWrite [as oncomplete] (net.js:864:14)
```
this err showed up and `hexo s` is shutdown after another few line of ``INFO update Optimize IMG......``

**Comment by HarborZeng** [comment]
additional: the only config I used is `all_minifier: true`

additional additional: I tried `hexo clean` and it didn't show more useful information when I run `hexo s --watch --debug` this way.

**Comment by wjykl22** [comment]
Have you solve it?
