### ISSUE TITLE
ECONNRESET : thrown with image_minifier enable

### ISSUE THREAD

**Issue by baptistedonaux** [chenzhutian/hexo-all-minifier#9]
When I enable `image_minifier`, few images are optimized and at one momert, this error is displayed.

``` json
# package.json
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "hexo": {
    "version": "3.2.0"
  },
  "dependencies": {
    "hexo": "^3.2.0",
    "hexo-all-minifier": "0.0.12",
    "hexo-cli": "^1.0.1",
    "hexo-generator-archive": "^0.1.4",
    "hexo-generator-category": "^0.1.3",
    "hexo-generator-index": "^0.2.0",
    "hexo-generator-sitemap": "^1.1.2",
    "hexo-generator-tag": "^0.2.0",
    "hexo-migrator-wordpress": "^0.1.2",
    "hexo-renderer-ejs": "^0.2.0",
    "hexo-renderer-marked": "^0.2.10",
    "hexo-renderer-stylus": "^0.3.1",
    "hexo-server": "^0.2.0"
  }
}

```

```
# _config.yml
image_minifier:
  enable: true
  interlaced: false
  multipass: false
  optimizationLevel: 7
  pngquant: false
  progressive: false
```

``` bash
$ hexo generate
INFO  Start processing
INFO  update Optimize HTML: /data/source/_drafts/docker-initiation.md [ 0.81% saved]
INFO  update Optimize HTML: /data/source/_posts/autocomplete-puissant-leger.md [ 0.35% saved]
INFO  update Optimize HTML: /data/source/_posts/behat-error-using-switchtoiframe.md [ 0.86% saved]
INFO  update Optimize HTML: /data/source/_posts/bonne-pratique-typer-parametres.md [ 0.25% saved]
INFO  update Optimize HTML: /data/source/_posts/gerer-cache-symfony2-doctrine2.md [ 0.28% saved]
INFO  update Optimize HTML: /data/source/_posts/gitlab-upgrade-error-problem-ssl-ca-cert.md [ -0.07% saved]
INFO  update Optimize HTML: /data/source/_posts/golang-extraire-les-donnees-dun-flux-rss.md [ -0.02% saved]
INFO  update Optimize HTML: /data/source/_posts/grunt-symfony-remplacer-assetic.md [ 0.08% saved]
INFO  update Optimize HTML: /data/source/_posts/here-we-go.md [ 0.57% saved]
INFO  update Optimize HTML: /data/source/_posts/implementer-userprovider.md [ 0.07% saved]
INFO  update Optimize HTML: /data/source/_posts/importer-sql-server-timestamp.md [ 0.23% saved]
INFO  update Optimize HTML: /data/source/_posts/injecter-du-twig-dans-du-javascript-assetic.md [ 0.15% saved]
INFO  update Optimize HTML: /data/source/_posts/mappingexception-class-y-sub-class-of-x-is-not-valid-entity-or-mapped-super-class.md [ -0.18% saved]
INFO  update Optimize HTML: /data/source/_posts/php-decompresser-archive-zip.md [ 0.22% saved]
INFO  update Optimize HTML: /data/source/_posts/php-encodage-error.md [ 0.30% saved]
INFO  update Optimize HTML: /data/source/_posts/php-enlever-les-caracteres-insecables.md [ -0.02% saved]
INFO  update Optimize HTML: /data/source/_posts/php-symfony2-iis.md [ 0.13% saved]
INFO  update Optimize HTML: /data/source/_posts/posgresql-postgis-geometry-type-doesnt-exist.md [ 0.29% saved]
INFO  update Optimize HTML: /data/source/_posts/raspberry-pi-gerer-lalimentation-des-ports-usb.md [ 0.71% saved]
INFO  update Optimize HTML: /data/source/_posts/script-php-high-performance.md [ 0.29% saved]
INFO  update Optimize HTML: /data/source/_posts/securitycontroller-implementation.md [ 0.12% saved]
INFO  update Optimize HTML: /data/source/_posts/soft-delete-comment-se-passer-de-gedmo-dans-symfony.md [ -0.08% saved]
INFO  update Optimize HTML: /data/source/_posts/sql-server-et-php.md [ 0.54% saved]
INFO  update Optimize HTML: /data/source/_posts/symfony2-bonnes-pratiques.md [ 0.70% saved]
INFO  update Optimize HTML: /data/source/_posts/symfony-recommandation-officielle.md [ 0.46% saved]
INFO  update Optimize HTML: /data/source/_posts/symfony2-bonne-pratique-deplacer-session.md [ 0.25% saved]
INFO  update Optimize HTML: /data/source/_posts/symfony2-service-container.md [ 0.36% saved]
INFO  update Optimize HTML: /data/source/_posts/tutoriel-docker-symfony-docker-compose.md [ 0.21% saved]
INFO  update Optimize HTML: /data/source/_posts/twig-accelerer-generation-templates.md [ 0.02% saved]
INFO  update Optimize HTML: /data/source/_posts/twig-include-performance.md [ 0.05% saved]
INFO  update Optimize HTML: /data/source/_posts/twig-render-controller-le-faux-bon-ami.md [ 0.37% saved]
INFO  update Optimize HTML: /data/source/_posts/typematrix-bepo-french-layout.md [ 1.61% saved]
INFO  update Optimize HTML: /data/source/_posts/virtualbox-peripherique-detecte.md [ 0.28% saved]
INFO  update Optimize HTML: /data/source/_posts/xcache-windows.md [ 0.57% saved]
INFO  update Optimize IMG: fancybox/fancybox_loading@2x.gif [ 16.48% saved]
INFO  update Optimize IMG: fancybox/fancybox_loading.gif [ 32.16% saved]
INFO  update Optimize IMG: php-symfony2-iis/php_iis-300x118.jpg [ 44.87% saved]
INFO  update Optimize IMG: soft-delete-comment-se-passer-de-gedmo-dans-symfony/doctrine.jpg [ 46.87% saved]
INFO  update Optimize IMG: symfony2-bonnes-pratiques/20-20.jpg [ 46.22% saved]
INFO  update Optimize IMG: raspberry-pi-gerer-lalimentation-des-ports-usb/raspberry_pi_Pi_USB_side_noted-2.jpg [ 61.92% saved]
INFO  update Optimize IMG: script-php-high-performance/binary_min.jpg [ 50.29% saved]
INFO  update Optimize IMG: css/fonts/fontawesome-webfont.svg [ 99.98% saved]
INFO  update Optimize IMG: grunt-symfony-remplacer-assetic/Symfony-Grunt.jpg [ 40.51% saved]
INFO  update Optimize IMG: xcache-windows/xcache.jpg [ 46.46% saved]
INFO  update Optimize IMG: fancybox/fancybox_overlay.png [ 90.53% saved]
INFO  update Optimize IMG: golang-extraire-les-donnees-dun-flux-rss/gopher.jpg [ 55.18% saved]
INFO  update Optimize IMG: css/images/banner.jpg [ 67.42% saved]
INFO  update Optimize IMG: autocomplete-puissant-leger/autocomplete.png [ 37.39% saved]
INFO  update Optimize IMG: fancybox/fancybox_sprite@2x.png [ 0.69% saved]
FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html
Error: read ECONNRESET
    at exports._errnoException (util.js:890:11)
    at Pipe.onread (net.js:552:26)
FATAL read ECONNRESET
Error: read ECONNRESET
    at exports._errnoException (util.js:890:11)
    at Pipe.onread (net.js:552:26)
```

**Comment by unhealthy** [comment]
now the plugin has been updated and some bugs have been fixed.
Do you still have this bug?
